# Generated by Django 5.2.13 on 2026-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userreferrals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Вік"
            ),
        ),
    ]
