repos:
  - repo: local
    hooks:
      - id: django-makemigrations-check
        name: Django makemigrations check
        entry: python manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false
