bind = "0.0.0.0:8000"
workers = 3  # (2 × CPU cores) + 1
threads = 2
worker_class = "gthread"
max_requests = 1000
max_requests_jitter = 50
timeout = 60
accesslog = "-"
errorlog = "-"
loglevel = "info"