# Generated by Django 5.2.3 on 2026-01-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("session_key", models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
