# Generated by Django 5.2.9 on 2026-01-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="currency",
        ),
    ]
