# Generated by Django 5.2.9 on 2026-02-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
