# Generated by Django 5.2.9 on 2026-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_delete_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=1500, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Назва товару"),
        ),
    ]
