# Generated by Django 5.2.9 on 2026-02-14 18:24

import django.core.validators
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_description_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    ),
                    shop.models.validate_image_size,
                    shop.models.validate_image_dimensions,
                ],
                verbose_name="Зображення",
            ),
        ),
    ]
