# Generated by Django 5.2.9 on 2026-02-14 19:09

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[shop.models.validate_no_emoji],
                verbose_name="Назва товару",
            ),
        ),
    ]
