# Generated by Django 5.2.11 on 2026-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateField(
                auto_now_add=True, db_index=True, verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("new", "Новий"), ("used", "Б/В")],
                db_index=True,
                default="new",
                max_length=10,
            ),
        ),
    ]
