# Generated by Django 5.2.3 on 2026-01-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(default="Unknown", max_length=100)),
                (
                    "country_code",
                    models.CharField(default="XX", max_length=2, unique=True),
                ),
                ("flag", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "verbose_name": "Країна",
                "verbose_name_plural": "Країни",
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва регіону"),
                ),
                (
                    "state_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Код регіону (ISO/FIPS)~",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="geo.country",
                        verbose_name="Назва країни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регіон",
                "verbose_name_plural": "Регіони",
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва міста")),
                ("city", models.CharField(blank=True, max_length=255)),
                ("city_id", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="geo.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="geo.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Місто",
                "verbose_name_plural": "Міста",
                "db_table": "city",
            },
        ),
    ]
