# Generated by Django 5.2.3 on 2026-01-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["country__name", "region__name", "name"],
                "verbose_name": "Місто",
                "verbose_name_plural": "Міста",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Країна",
                "verbose_name_plural": "Країни",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ["country__name", "name"],
                "verbose_name": "Регіон",
                "verbose_name_plural": "Регіони",
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "region")},
        ),
        migrations.RemoveField(
            model_name="country",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="country",
            name="country_name",
        ),
        migrations.RemoveField(
            model_name="country",
            name="flag",
        ),
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(
                default="",
                max_length=22,
                unique=True,
                verbose_name="Код (ISO 3166-1 alpha-2)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="flag_emoji",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Емодзі прапора"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="name",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Назва країни"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="city_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                unique=True,
                verbose_name="Зовнішній ID (наприклад, GeoNames)",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.country",
                verbose_name="Назва країни",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.region",
                verbose_name="Назва регіону",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "country")},
        ),
        migrations.AlterModelTable(
            name="city",
            table="geo_city",
        ),
        migrations.AlterModelTable(
            name="country",
            table="geo_country",
        ),
        migrations.AlterModelTable(
            name="region",
            table="geo_region",
        ),
        migrations.RemoveField(
            model_name="city",
            name="city",
        ),
    ]
