# Generated by Django 5.2.9 on 2026-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_city_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Валюта"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="currency_symbol",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Символ валюти"
            ),
        ),
    ]
