# Generated by Django 5.2.9 on 2026-01-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_country_currency_country_currency_symbol"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
    ]
