# Generated by Django 5.2.9 on 2026-01-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_alter_city_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        max_length=255, verbose_name="Назва закладу/адреса"
                    ),
                ),
                (
                    "place_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Google Place ID"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=20, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Конкретна локація",
                "verbose_name_plural": "Конкретні локації",
                "db_table": "geo_location_place",
            },
        ),
    ]
