# Generated by Django 5.2.9 on 2026-01-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_locationplace"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationplace",
            options={
                "verbose_name": "Мітка на карті",
                "verbose_name_plural": "Мітки на карті",
            },
        ),
        migrations.AlterField(
            model_name="locationplace",
            name="latitude",
            field=models.DecimalField(
                decimal_places=16, max_digits=20, null=True, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="locationplace",
            name="longitude",
            field=models.DecimalField(
                decimal_places=16, max_digits=20, null=True, verbose_name="Довгота"
            ),
        ),
        migrations.AlterField(
            model_name="locationplace",
            name="place_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google Place ID",
            ),
        ),
        migrations.AlterField(
            model_name="locationplace",
            name="place_name",
            field=models.CharField(max_length=255, verbose_name="Назва або опис місця"),
        ),
    ]
