# Generated by Django 5.2.9 on 2026-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0006_alter_locationplace_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_translate",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Назва міста українською",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="name_translate",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Назва країни українською",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_translate",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Назва регіону українською",
            ),
        ),
    ]
