# Generated by Django 5.2.9 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0007_city_name_translate_country_name_translate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="state_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Код регіону (ISO/FIPS)",
            ),
        ),
    ]
